### ISSUE TITLE
module is not loaded error

### ISSUE THREAD

**Issue by drsiyarb** [fepegar/SlicerParcellation#2]
Hello thanks for the great work. 

I tried installing the module as instructed, but I get a module is not loaded error.
I tried installing on two different computers, one with a GPU and one without. 

Error log says "torchio not loaded", but I have installed torchio extension, opened torchio transforms module and waited for the extra packages to install. 

This error is same for both gpu and cpu computers.

Also, I tried setting the   `self.parent.dependencies = []` (removed TorchIO) in brainparcellation.py file.

Then the module is loaded, but now I get an
`Error running segmentation:
in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'`

here is the full error log:

```
Switch to module:  "BrainParcellation"
"Color" Reader has successfully read the file "C:\\Users\\USER\\AppData\\Local\\NA-MIC\\Slicer 5.1.0-2022-10-15\\NA-MIC\\Extensions-31206\\SlicerParcellation-master\\GIFNiftyNet.ctbl" "[0.01s]"

Loaded volume from file: C:\Users\USER\AppData\Local\Temp\OAS1_0145_MR2_mpr_n4_anon_sbj_111.nii.gz. Dimensions: 256x256x160. Number of components: 1. Pixel type: short.

"Volume" Reader has successfully read the file "C:\\Users\\USER\\AppData\\Local\\Temp\\OAS1_0145_MR2_mpr_n4_anon_sbj_111.nii.gz" "[0.14s]"

Importing torch...

PyTorch 1.12.1+cpu imported correctly
CUDA available: False
Inference might take some minutes as it will run on the CPU. Do you want to continue anyway?

Importing torch...
PyTorch 1.12.1+cpu imported correctly
CUDA available: False

C:\Users\USER\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-15\lib\Python\Lib\site-packages\torch\hub.py:266: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/fepegar/highresnet/zipball/master" to C:\Users\USER/.cache\torch\hub\master.zip

Downloading: "https://github.com/fepegar/highresnet-models/raw/master/highres3dnet_li_parameters-7d297872.pth" to C:\Users\USER/.cache\torch\hub\checkpoints\highres3dnet_li_parameters-7d297872.pth

Importing torchio...
Importing torch...
PyTorch 1.12.1+cpu imported correctly
CUDA available: False
TorchIO 0.18.84 imported correctly
Creating TorchIO image...

Error running segmentation:
in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'

Inference might take some minutes as it will run on the CPU. Do you want to continue anyway?

Creating TorchIO image...

Error running segmentation:
in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *
```

`

**Comment by fepegar** [comment]
Hi, @drsiyarb. Thanks for reporting. What version of Slicer are you using?

**Comment by cloudpanl** [comment]
I get the same error，my version of Slicer is Slicer 5.1.0-2022-08-29,I have TorchIO installed.

[WARNING][Qt] 25.10.2022 15:27:29 [] (unknown:0) - When loading module  "BrainParcellation" , the dependency "TorchIO" failed to be loaded.
[WARNING][VTK] 25.10.2022 15:27:29 [] (unknown:0) - Generic Warning: In D:\D\P\S-0\Base\Logic\vtkSlicerApplicationLogic.cxx, line 839
GetModuleHomeDirectory: failed to compute module home directory given filePath: D:/Program Files/SlicerParcellation/BrainResectionCavitySegmentation.py
[WARNING][VTK] 25.10.2022 15:27:29 [] (unknown:0) - Generic Warning: In D:\D\P\S-0\Base\Logic\vtkSlicerApplicationLogic.cxx, line 839
GetModuleHomeDirectory: failed to compute module home directory given filePath: D:/Program Files/SlicerParcellation/InferenceUtils.py

**Comment by drsiyarb** [comment]
Hi @fepegar I tried with both 5.0.3 and 5.11 but the problem persisted.

But in another computer, after I set `self.parent.dependencies = []` it worked. And succesfully completed a segmentation.

**Comment by fepegar** [comment]
Thank you all. I've updated the dependencies.
