### ISSUE TITLE
Not getting proper output

### ISSUE THREAD

**Issue by anuragp2018** [fepegar/SlicerParcellation#7]
Is any preprocessing required before running the module? I tried it on T1-weighted MRI, but it gave a different output compared to your sample data output.

![Screenshot (22)](https://github.com/fepegar/SlicerParcellation/assets/152591938/6467db36-ad31-41bf-ba20-b71ca8ec3321)

**Comment by fepegar** [comment]
No preprocessing is needed. But your image seems quite different to the training data, so bad results are not surprising. See [On the Compactness, Efficiency, and Representation of 3D Convolutional Networks: Brain Parcellation as a Pretext Task](https://arxiv.org/abs/1707.01992) for more information.
